// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VideoCallAPI.Data;

#nullable disable

namespace VideoCallAPI.Migrations
{
    [DbContext(typeof(VideoCallDbContext))]
    [Migration("20260826083937_ReconcileCurrentModel")]
    partial class ReconcileCurrentModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VideoCallAPI.Models.CallHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("call_type")
                        .HasColumnType("integer");

                    b.Property<int>("caller_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("duration")
                        .HasColumnType("integer");

                    b.Property<string>("end_reason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("end_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("receiver_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("caller_id");

                    b.HasIndex("receiver_id");

                    b.ToTable("CallHistories");
                });

            modelBuilder.Entity("VideoCallAPI.Models.ChatGroup", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("announcement")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("owner_id")
                        .HasColumnType("integer");

                    b.Property<bool>("pinned")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("owner_id", "created_at");

                    b.ToTable("ChatGroups");
                });

            modelBuilder.Entity("VideoCallAPI.Models.ChatGroupMember", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("group_id")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("joined_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("group_id", "user_id")
                        .IsUnique();

                    b.HasIndex("user_id", "is_active");

                    b.ToTable("ChatGroupMembers");
                });

            modelBuilder.Entity("VideoCallAPI.Models.ChatMessage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("duration")
                        .HasColumnType("integer");

                    b.Property<string>("file_path")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("file_size")
                        .HasColumnType("integer");

                    b.Property<bool>("is_read")
                        .HasColumnType("boolean");

                    b.Property<int>("receiver_id")
                        .HasColumnType("integer");

                    b.Property<string>("reply_to_content")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("reply_to_file_path")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("reply_to_message_id")
                        .HasColumnType("integer");

                    b.Property<string>("reply_to_sender_name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("reply_to_type")
                        .HasColumnType("integer");

                    b.Property<int>("sender_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("reply_to_message_id");

                    b.HasIndex("receiver_id", "sender_id", "timestamp");

                    b.HasIndex("sender_id", "receiver_id", "timestamp");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("VideoCallAPI.Models.Contact", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("added_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("contact_user_id")
                        .HasColumnType("integer");

                    b.Property<string>("display_name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("is_blocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("last_message_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("unread_count")
                        .HasColumnType("integer");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("contact_user_id");

                    b.HasIndex("user_id", "contact_user_id")
                        .IsUnique();

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("VideoCallAPI.Models.EmailVerificationCode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("code_hash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_used")
                        .HasColumnType("boolean");

                    b.Property<int>("purpose")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("used_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("is_used", "expires_at");

                    b.HasIndex("email", "purpose", "expires_at");

                    b.ToTable("EmailVerificationCodes");
                });

            modelBuilder.Entity("VideoCallAPI.Models.FavoriteItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("file_path")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("file_size")
                        .HasColumnType("integer");

                    b.Property<string>("source_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("user_id", "created_at");

                    b.HasIndex("user_id", "type");

                    b.ToTable("FavoriteItems");
                });

            modelBuilder.Entity("VideoCallAPI.Models.FriendRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("note")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("receiver_id")
                        .HasColumnType("integer");

                    b.Property<int>("requester_id")
                        .HasColumnType("integer");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("requester_id", "receiver_id")
                        .IsUnique();

                    b.HasIndex("receiver_id", "status", "created_at");

                    b.HasIndex("requester_id", "status", "created_at");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("VideoCallAPI.Models.GroupChatMessage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("duration")
                        .HasColumnType("integer");

                    b.Property<string>("file_path")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("file_size")
                        .HasColumnType("integer");

                    b.Property<int>("group_id")
                        .HasColumnType("integer");

                    b.Property<string>("reply_to_content")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("reply_to_file_path")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("reply_to_message_id")
                        .HasColumnType("integer");

                    b.Property<string>("reply_to_sender_name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("reply_to_type")
                        .HasColumnType("integer");

                    b.Property<int>("sender_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("reply_to_message_id");

                    b.HasIndex("sender_id");

                    b.HasIndex("group_id", "created_at");

                    b.ToTable("GroupChatMessages");
                });

            modelBuilder.Entity("VideoCallAPI.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_used")
                        .HasColumnType("boolean");

                    b.Property<string>("token_hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("used_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("token_hash")
                        .IsUnique();

                    b.HasIndex("is_used", "expires_at");

                    b.HasIndex("user_id", "expires_at");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("VideoCallAPI.Models.Room", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int>("max_participants")
                        .HasColumnType("integer");

                    b.Property<string>("room_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("room_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.HasIndex("created_by");

                    b.HasIndex("room_code")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("VideoCallAPI.Models.RoomParticipant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("joined_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("left_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("room_id")
                        .HasColumnType("integer");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.HasIndex("room_id", "user_id", "is_active");

                    b.ToTable("RoomParticipants");
                });

            modelBuilder.Entity("VideoCallAPI.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("avatar_path")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("birthday")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("display_name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("email_verified_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("is_online")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("last_heartbeat_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("last_login_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("province")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("qq_avatar_url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("qq_bound_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("qq_nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("qq_open_id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("qq_union_id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("region")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("signature")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("qq_open_id")
                        .IsUnique()
                        .HasFilter("\"qq_open_id\" IS NOT NULL");

                    b.HasIndex("qq_union_id")
                        .IsUnique()
                        .HasFilter("\"qq_union_id\" IS NOT NULL");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("VideoCallAPI.Models.CallHistory", b =>
                {
                    b.HasOne("VideoCallAPI.Models.User", "Caller")
                        .WithMany("InitiatedCalls")
                        .HasForeignKey("caller_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoCallAPI.Models.User", "receiver")
                        .WithMany("ReceivedCalls")
                        .HasForeignKey("receiver_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caller");

                    b.Navigation("receiver");
                });

            modelBuilder.Entity("VideoCallAPI.Models.ChatGroup", b =>
                {
                    b.HasOne("VideoCallAPI.Models.User", "owner")
                        .WithMany("OwnedChatGroups")
                        .HasForeignKey("owner_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("VideoCallAPI.Models.ChatGroupMember", b =>
                {
                    b.HasOne("VideoCallAPI.Models.ChatGroup", "group")
                        .WithMany("members")
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoCallAPI.Models.User", "user")
                        .WithMany("ChatGroupMembers")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("group");

                    b.Navigation("user");
                });

            modelBuilder.Entity("VideoCallAPI.Models.ChatMessage", b =>
                {
                    b.HasOne("VideoCallAPI.Models.User", "receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("receiver_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoCallAPI.Models.User", "sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("sender_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("receiver");

                    b.Navigation("sender");
                });

            modelBuilder.Entity("VideoCallAPI.Models.Contact", b =>
                {
                    b.HasOne("VideoCallAPI.Models.User", "contact_user")
                        .WithMany("ContactedBy")
                        .HasForeignKey("contact_user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoCallAPI.Models.User", "User")
                        .WithMany("Contacts")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("contact_user");
                });

            modelBuilder.Entity("VideoCallAPI.Models.FavoriteItem", b =>
                {
                    b.HasOne("VideoCallAPI.Models.User", "user")
                        .WithMany("FavoriteItems")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("VideoCallAPI.Models.FriendRequest", b =>
                {
                    b.HasOne("VideoCallAPI.Models.User", "receiver")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("receiver_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoCallAPI.Models.User", "requester")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("requester_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("receiver");

                    b.Navigation("requester");
                });

            modelBuilder.Entity("VideoCallAPI.Models.GroupChatMessage", b =>
                {
                    b.HasOne("VideoCallAPI.Models.ChatGroup", "group")
                        .WithMany("messages")
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoCallAPI.Models.User", "sender")
                        .WithMany("SentGroupMessages")
                        .HasForeignKey("sender_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("group");

                    b.Navigation("sender");
                });

            modelBuilder.Entity("VideoCallAPI.Models.PasswordResetToken", b =>
                {
                    b.HasOne("VideoCallAPI.Models.User", "user")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("VideoCallAPI.Models.Room", b =>
                {
                    b.HasOne("VideoCallAPI.Models.User", "creator")
                        .WithMany()
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("creator");
                });

            modelBuilder.Entity("VideoCallAPI.Models.RoomParticipant", b =>
                {
                    b.HasOne("VideoCallAPI.Models.Room", "Room")
                        .WithMany("participants")
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoCallAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VideoCallAPI.Models.ChatGroup", b =>
                {
                    b.Navigation("members");

                    b.Navigation("messages");
                });

            modelBuilder.Entity("VideoCallAPI.Models.Room", b =>
                {
                    b.Navigation("participants");
                });

            modelBuilder.Entity("VideoCallAPI.Models.User", b =>
                {
                    b.Navigation("ChatGroupMembers");

                    b.Navigation("ContactedBy");

                    b.Navigation("Contacts");

                    b.Navigation("FavoriteItems");

                    b.Navigation("InitiatedCalls");

                    b.Navigation("OwnedChatGroups");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("ReceivedCalls");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("SentGroupMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
