param(
    [string]$ProjectName = "foreverlove-chat",
    [string]$AppVersion = "",
    [string]$ImageTag = "",
    [string]$ApiPublicUrl = "",
    [string]$WebPublicUrl = "",
    [string]$ApiPort = "",
    [string]$WebPort = "",
    [switch]$SkipBuild
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir = Split-Path -Parent $ScriptDir
$EnvFile = Join-Path $RootDir ".env"
$VersionFile = Join-Path $RootDir "VERSION"
$IsWindowsPlatform = [System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform(
    [System.Runtime.InteropServices.OSPlatform]::Windows)

function Write-DeployLog {
    param([string]$Message)
    Write-Host "[deploy-local] $Message"
}

function New-RandomSecret {
    param([int]$Bytes = 48)

    $buffer = New-Object byte[] $Bytes
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($buffer)
    }
    finally {
        $rng.Dispose()
    }
    [Convert]::ToBase64String($buffer)
}

function Read-DotEnv {
    param([string]$Path)

    $values = @{}
    if (-not (Test-Path -LiteralPath $Path)) {
        return $values
    }

    foreach ($line in Get-Content -LiteralPath $Path) {
        $trimmed = $line.Trim()
        if ($trimmed.Length -eq 0 -or $trimmed.StartsWith("#")) {
            continue
        }

        $parts = $trimmed.Split("=", 2)
        if ($parts.Count -eq 2 -and $parts[0].Trim().Length -gt 0) {
            $values[$parts[0].Trim()] = $parts[1].Trim()
        }
    }

    $values
}

function Add-DotEnvValue {
    param(
        [string]$Path,
        [string]$Name,
        [string]$Value
    )

    Add-Content -LiteralPath $Path -Value "$Name=$Value"
}

function Ensure-EnvFile {
    param([string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        $initialSecret = New-RandomSecret
        $initialPostgresPassword = New-RandomSecret -Bytes 24
        @(
            "# Generated by scripts/deploy-local.ps1. This file is ignored by git.",
            "POSTGRES_DB=foreverlove_chat",
            "POSTGRES_USER=postgres",
            "POSTGRES_PASSWORD=$initialPostgresPassword",
            "POSTGRES_PORT=54329",
            "POSTGRES_BIND_HOST=127.0.0.1",
            "API_ENVIRONMENT=Production",
            "API_PORT=7001",
            "API_BIND_HOST=0.0.0.0",
            "WEB_PORT=7002",
            "WEB_BIND_HOST=0.0.0.0",
            "JWT_SECRET=$initialSecret",
            "JWT_ISSUER=VideoCallAPI",
            "JWT_AUDIENCE=VideoCallClient",
            "SWAGGER_ENABLED=false",
            "USE_HTTPS_REDIRECTION=false",
            "EXTRA_CORS_ORIGIN=http://common.wangbank.top"
        ) | Set-Content -LiteralPath $Path -Encoding utf8
        Write-DeployLog "Created .env with generated local secrets."
        return
    }

    $values = Read-DotEnv -Path $Path
    if (-not $values.ContainsKey("JWT_SECRET") -and [string]::IsNullOrWhiteSpace($env:JWT_SECRET)) {
        Add-DotEnvValue -Path $Path -Name "JWT_SECRET" -Value (New-RandomSecret)
        Write-DeployLog "Added JWT_SECRET to .env."
    }

    if (-not $values.ContainsKey("POSTGRES_PASSWORD") -and [string]::IsNullOrWhiteSpace($env:POSTGRES_PASSWORD)) {
        Add-DotEnvValue -Path $Path -Name "POSTGRES_PASSWORD" -Value (New-RandomSecret -Bytes 24)
        Write-DeployLog "Added POSTGRES_PASSWORD to .env."
    }
}

function Resolve-Setting {
    param(
        [string]$ExplicitValue,
        [string]$EnvName,
        [hashtable]$DotEnv,
        [string]$DefaultValue
    )

    if (-not [string]::IsNullOrWhiteSpace($ExplicitValue)) {
        return $ExplicitValue
    }

    $envValue = [Environment]::GetEnvironmentVariable($EnvName)
    if (-not [string]::IsNullOrWhiteSpace($envValue)) {
        return $envValue
    }

    if ($DotEnv.ContainsKey($EnvName) -and -not [string]::IsNullOrWhiteSpace([string]$DotEnv[$EnvName])) {
        return [string]$DotEnv[$EnvName]
    }

    $DefaultValue
}

function Get-ShortGitSha {
    try {
        $sha = (& git -C $RootDir rev-parse --short HEAD 2>$null)
        if ($LASTEXITCODE -eq 0 -and -not [string]::IsNullOrWhiteSpace($sha)) {
            return $sha.Trim()
        }
    }
    catch {
    }

    "local"
}

function Get-LanAddress {
    if ($IsWindowsPlatform) {
        $ip = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
            Where-Object {
                $_.IPAddress -notmatch "^(127\.|169\.254\.)" -and
                $_.IPAddress -notmatch "^172\.(1[6-9]|2[0-9]|3[0-1])\." -and
                $_.IPAddress -notmatch "^10\." -and
                $_.IPAddress -notmatch "^192\.0\.0\."
            } |
            Sort-Object InterfaceMetric |
            Select-Object -First 1 -ExpandProperty IPAddress

        if (-not [string]::IsNullOrWhiteSpace($ip)) {
            return $ip
        }

        $fallback = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
            Where-Object { $_.IPAddress -notmatch "^(127\.|169\.254\.)" } |
            Sort-Object InterfaceMetric |
            Select-Object -First 1 -ExpandProperty IPAddress

        if (-not [string]::IsNullOrWhiteSpace($fallback)) {
            return $fallback
        }
    }

    "localhost"
}

function ConvertTo-DockerTag {
    param([string]$Value)

    $tag = $Value -replace "[^A-Za-z0-9_.-]", "-"
    $tag = $tag.Trim(".", "-", "_")
    if ($tag.Length -gt 120) {
        $tag = $tag.Substring(0, 120)
    }

    if ([string]::IsNullOrWhiteSpace($tag)) {
        return "local"
    }

    $tag
}

function Wait-HttpOk {
    param(
        [string]$Name,
        [string]$Url,
        [int]$TimeoutSeconds = 180
    )

    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    while ((Get-Date) -lt $deadline) {
        try {
            $response = Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 5
            if ($response.StatusCode -ge 200 -and $response.StatusCode -lt 400) {
                Write-DeployLog "$Name is ready: $Url"
                return
            }
        }
        catch {
        }

        Start-Sleep -Seconds 2
    }

    docker compose --project-name $ProjectName logs --tail 120 api
    throw "$Name did not become ready in $TimeoutSeconds seconds: $Url"
}

function Set-Env {
    param(
        [string]$Name,
        [string]$Value
    )

    [Environment]::SetEnvironmentVariable($Name, $Value, "Process")
}

Set-Location -LiteralPath $RootDir
Ensure-EnvFile -Path $EnvFile
$DotEnv = Read-DotEnv -Path $EnvFile

foreach ($secretName in @("JWT_SECRET", "POSTGRES_PASSWORD", "POSTGRES_DB", "POSTGRES_USER")) {
    $currentValue = [Environment]::GetEnvironmentVariable($secretName)
    if ([string]::IsNullOrWhiteSpace($currentValue) -and $DotEnv.ContainsKey($secretName)) {
        Set-Env -Name $secretName -Value ([string]$DotEnv[$secretName])
    }
}

$baseVersion = "1.0.0"
if (Test-Path -LiteralPath $VersionFile) {
    $baseVersion = (Get-Content -LiteralPath $VersionFile -Raw).Trim()
}

if ([string]::IsNullOrWhiteSpace($AppVersion)) {
    $runNumber = $env:GITHUB_RUN_NUMBER
    $shortSha = if (-not [string]::IsNullOrWhiteSpace($env:GITHUB_SHA) -and $env:GITHUB_SHA.Length -ge 7) {
        $env:GITHUB_SHA.Substring(0, 7)
    }
    else {
        Get-ShortGitSha
    }

    if (-not [string]::IsNullOrWhiteSpace($runNumber)) {
        $AppVersion = "$baseVersion+$runNumber.$shortSha"
    }
    else {
        $stamp = Get-Date -Format "yyyyMMddHHmmss"
        $AppVersion = "$baseVersion+local.$stamp.$shortSha"
    }
}

if ([string]::IsNullOrWhiteSpace($ImageTag)) {
    $ImageTag = ConvertTo-DockerTag -Value $AppVersion
}

$ApiPort = Resolve-Setting -ExplicitValue $ApiPort -EnvName "API_PORT" -DotEnv $DotEnv -DefaultValue "7001"
$WebPort = Resolve-Setting -ExplicitValue $WebPort -EnvName "WEB_PORT" -DotEnv $DotEnv -DefaultValue "7002"

$hostAddress = Get-LanAddress
if ([string]::IsNullOrWhiteSpace($ApiPublicUrl)) {
    $ApiPublicUrl = Resolve-Setting -ExplicitValue "" -EnvName "API_PUBLIC_URL" -DotEnv $DotEnv -DefaultValue "http://${hostAddress}:$ApiPort"
}

if ([string]::IsNullOrWhiteSpace($WebPublicUrl)) {
    $WebPublicUrl = Resolve-Setting -ExplicitValue "" -EnvName "WEB_PUBLIC_URL" -DotEnv $DotEnv -DefaultValue "http://${hostAddress}:$WebPort"
}

$ApiPublicUrl = $ApiPublicUrl.TrimEnd("/")
$WebPublicUrl = $WebPublicUrl.TrimEnd("/")
$SignalRPublicUrl = Resolve-Setting -ExplicitValue "" -EnvName "SIGNALR_PUBLIC_URL" -DotEnv $DotEnv -DefaultValue "$ApiPublicUrl/videocallhub"
$SignalRPublicUrl = $SignalRPublicUrl.TrimEnd("/")
$vcsRef = if (-not [string]::IsNullOrWhiteSpace($env:GITHUB_SHA)) { $env:GITHUB_SHA } else { Get-ShortGitSha }

Set-Env -Name "APP_VERSION" -Value $AppVersion
Set-Env -Name "IMAGE_TAG" -Value $ImageTag
Set-Env -Name "VCS_REF" -Value $vcsRef
Set-Env -Name "API_PORT" -Value $ApiPort
Set-Env -Name "WEB_PORT" -Value $WebPort
Set-Env -Name "API_PUBLIC_URL" -Value $ApiPublicUrl
Set-Env -Name "WEB_PUBLIC_URL" -Value $WebPublicUrl
Set-Env -Name "SIGNALR_PUBLIC_URL" -Value $SignalRPublicUrl

Write-DeployLog "Version: $AppVersion"
Write-DeployLog "Image tag: $ImageTag"
Write-DeployLog "API public URL: $ApiPublicUrl"
Write-DeployLog "Website public URL: $WebPublicUrl"

$composeArgs = @("compose", "--project-name", $ProjectName, "up", "-d", "--remove-orphans")
if (-not $SkipBuild) {
    $composeArgs += "--build"
}

docker @composeArgs
if ($LASTEXITCODE -ne 0) {
    throw "docker compose failed with exit code $LASTEXITCODE"
}

Wait-HttpOk -Name "API" -Url "http://127.0.0.1:$ApiPort/health" -TimeoutSeconds 180
Wait-HttpOk -Name "Website" -Url "http://127.0.0.1:$WebPort/health" -TimeoutSeconds 120

docker compose --project-name $ProjectName ps

Write-DeployLog "Deployment complete."
Write-DeployLog "Website: $WebPublicUrl"
Write-DeployLog "API: $ApiPublicUrl"
Write-DeployLog "Flutter API define: --dart-define=API_BASE_URL=$ApiPublicUrl/api"
Write-DeployLog "Flutter SignalR define: --dart-define=SIGNALR_HUB_URL=$SignalRPublicUrl"
